---
- name: Basic operations
  hosts: all
  # gather_facts: false
  become: yes

  tasks:  
    - name: Classify hosts depending on their OS distro
      group_by:
        key: os_{{ ansible_facts['distribution'] }}
      register: os_distro
    
    - name: List OS distributions
      debug:
        var: os_distro
      
- name: Operations with YUM
  hosts: os_RedHat

  tasks:
    - name: Get a list of installed RPM packages      
      yum:
        list: installed
      register: rmp_packages
    
    # - name: Print installed RPM packages 
    #   debug:
    #     var: rpm_packages
    
# - name: Operations with APT
#   hosts: os_Ubuntu

#   tasks:
#     - name: Get a list of installed DEB packages
#       apt:
#         state: present
#       register: deb_packages
    
#     - name: Print insstalled DEB packages
#       debug:
#         var: deb_packages

- name: Make sure that ssh service is running
  hosts: all

  tasks:
    - name: Make sure that ssh service is running
      systemd:
        state: started
        name: sshd
