# Use this playbook to delete users on the remote servers.

---
- name: Delete users
  hosts: physical

  tasks:
    - name: Delete User
      user:
        name: "{{ username }}"
        state: absent
        remove: yes
...
