# Use this playbook to delete users on the remote servers.

---
- name: Delete users
  hosts: all

  tasks:
    - name: Delete User
      user:
        name: "{{ username }}"
        state: present
        remove: yes
...
