# This playbook gathers facts of remote host(s) and displays some properties.

---
- name: Display some basic facts
  hosts: 192.168.1.45
  tasks:

    - name: "{{ inventory_hostname }}"
      debug:
        msg: "{{ ansible_facts['fqdn'] }}"
...