# This playbook gathers facts of remote host(s) and displays some properties.

---
- name: Display some basic facts
  hosts: mlrd
  tasks:

    - name: "Properties of {{ inventory_hostname }}"
      debug:
        msg: "{{ ansible_facts['fqdn'] }}"
...