# This playbook gathers facts of remote host(s) and displays some properties.

---
- name: Display some basic facts
  hosts: 192.168.1.45
  tasks:

    - name: Show properties of MLRD
      debug:
        msg: >
          My FQDN is {{ ansible_facts['fqdn'] }}
          and my default IP address is {{ ansible_facts['default_ipf4']['address'] }}
...