# This playbook will install the latest updates based on package manager.

- name: Gather information about hosts
  hosts: all
  become: true
  tasks:

    - name: Classify hosts depending on their OS distro
      group_by:
        key: os_{{ ansible_facts['distribution'] }}
      register: os_distro

#    - name: List OS distribution
#      debug:
#        var: os_distro

- name: Patch APT servers
  hosts: os_Ubuntu
  tasks:

    - name: Update cache and upgrage all packages
      register: updatesys
      apt:
        name: "*"
        state: latest
        update_cache: true

    - name: Show the content of capturedi in updatesys
      debug:
        var: updatesys

    - name: Display the upgrade stats
      debug:
        msg: "{{ updatesys.stdout_lines | *upgraded* }}"
...
