# This playbook will install the latest updates based on package manager.

- name: Gather information about hosts
  hosts: all
  become: true
  tasks:

    - name: Classify hosts depending on their OS distro
      group_by:
        key: os_{{ ansible_facts['distribution'] }}
      register: os_distro

#    - name: List OS distribution
#      debug:
#        var: os_distro

- name: Patch APT servers
  hosts: os_Ubuntu
  tasks:

    - name: Upgrade all packages to the latest version
      apt:
        update_cache: true
        name: "*"
        state: latest
      register: apt_upgrade_result

    - name: List upgraded packages
      debug:
        var: apt_upgrade_result
