# This playbook creates a user using encrypted variables stored in an ansible-vault encrypted file.

---
- name: Create users
  hosts: 192.168.1.60

  tasks:
    - name: Create a user
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        state: present
...
