## This playbook will install HTTPD and test connection to the server.

---
- name: Setup web server
  hosts: web
  tasks:

    - name: Install httpd
      yum:
        name: httpd

    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: true

    - name: Install sample content
      copy:
        dest: /var/www/html/index.html
        content: "Ratamahata\n"

    - name: Create firewall rules
      firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true

- name: Test connectivity to webserver
  hosts: localhost
  become: false
  tasks:

    - name: Connect to webserver
      uri:
        url: http://192.168.1.41
        return_content: yes
        status_code: 200
...
