---
- name: Basic operations
  hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: Make sure that ssh service is running
      systemd:
        state: started
        name: sshd
    
    - name: Get a list of installed YUM packages
      yum:
        list: installed
      register: yum_packages
    
    -  name: List installed YUM packages 
       debug:
         var: yum_packages
