---
- name: Basic operations
  hosts: all
  gather_facts: true
  become: yes

  tasks:  
    - name: Classify hosts depending on their OS distro
      group_by:
        key: os_{{ ansible_facts['distribution'] }}
      register: os_distro
    
    - name: List OS distributions
      debug:
        var: os_distro
      
- name: Operations with YUM
  hosts: os_RedHat

  tasks:
    - name: Get a list of installed YUM packages      
      yum:
        list: installed
      register: yum_packages
    
    - name: List installed YUM packages 
      debug:
        var: yum_packages

    - name: Make sure that ssh service is running
      systemd:
        state: started
        name: sshd