---
- name: Check services status
  hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: Make sure that ssh service is running
      systemd:
        state: started
        name: sshd

