# This playbook shows simple variables example.
# Result of this playbook:
# Packages specified in "vars" will be installed on the hosts form the rpm group.
# All variables are specified inside the play.

---
- name: Simple variable example
  hosts: rpm
  vars:
    packages:
      - nmap
      - httpd
      - php
      - mod_php
      - mod_ssl
  tasks:

    - name: Install software
      yum:
        name: "{{ packages }}"
        state: present
...
