# Result of this playbook:
# Package "nmap" will be installed on all the hosts in the mlrd group.
# Package "sysstat" will be installed on the .60 host only.
# This is because hosts_var dir contains a file with the name of the specific host.
# Package "tree" will be installed on the rest of the hosts specified in the inventory file.

---
- name: Simple variable example
  hosts: all
  tasks:

    - name: Install software
      yum:
        name: "{{ packages }}"
        state: present
...
